"""scori fix — create a GitHub pull request with recommended dependency updates.

Workflow:
  1. Resolve updates via scori order (lowest-friction first)
  2. Create a new branch from the current base
  3. Apply version bumps to manifest files
  4. Commit, push, and open a PR via the GitHub REST API

Requires GITHUB_TOKEN with `contents: write` and `pull-requests: write` scope.
In --dry-run mode (the default) no git operations are performed.
"""

from __future__ import annotations

import os
import re
import subprocess
from pathlib import Path
from typing import Any

import requests

from ._types import FrictionResult


def _git(args: list[str], cwd: Path) -> tuple[int, str]:
    result = subprocess.run(
        ["git", *args],
        cwd=cwd,
        capture_output=True,
        text=True,
    )
    return result.returncode, result.stdout.strip()


def current_branch(project_root: Path) -> str:
    _, branch = _git(["rev-parse", "--abbrev-ref", "HEAD"], project_root)
    return branch or "main"


def has_uncommitted_changes(project_root: Path) -> bool:
    _, output = _git(["status", "--porcelain"], project_root)
    return bool(output.strip())


def detect_github_remote(project_root: Path) -> tuple[str, str] | None:
    """Return (owner, repo) parsed from the origin remote URL, or None."""
    _, url = _git(["remote", "get-url", "origin"], project_root)
    if not url:
        return None
    m = re.search(r"github\.com[:/]([^/]+)/([^/.]+)", url)
    if not m:
        return None
    return m.group(1), m.group(2).removesuffix(".git")


def _update_line(line: str, package: str, new_version: str) -> str | None:
    """Rewrite one manifest line to pin package at new_version, or return None."""
    pkg_pat = r"[-_.]".join(re.escape(part) for part in re.split(r"[-_.]", package))
    m = re.match(
        r'^(\s*["\']?)(' + pkg_pat + r")(\[.*?\])?(\s*)"
        r'(==|>=|~=|!=|<=|>|<)([^\s,;"\'\\]+)',
        line,
        re.IGNORECASE,
    )
    if not m:
        return None
    prefix = line[: m.start(5)]
    suffix = line[m.end() :]
    return f"{prefix}=={new_version}{suffix}"


def _apply_updates(
    project_root: Path,
    updates: list[tuple[str, str, str, str]],
) -> int:
    """Write version bumps to manifest files. Returns number of lines changed."""
    # Group by file so each manifest is read and written exactly once.
    by_file: dict[str, list[tuple[str, str]]] = {}
    for name, _current, latest, source_file in updates:
        if source_file:
            by_file.setdefault(source_file, []).append((name, latest))

    applied = 0
    for source_file, pkg_updates in by_file.items():
        manifest = project_root / source_file
        if not manifest.exists():
            continue
        original = manifest.read_text(encoding="utf-8")
        lines = original.splitlines(keepends=True)
        for name, latest in pkg_updates:
            for i, line in enumerate(lines):
                new_line = _update_line(line, name, latest)
                if new_line is not None:
                    lines[i] = new_line
                    applied += 1
                    break
        updated = "".join(lines)
        if len(updated) < len(original):
            raise RuntimeError(
                f"Safety check: {manifest.name} would shrink "
                f"({len(original)} → {len(updated)} bytes). Aborting write."
            )
        manifest.write_text(updated, encoding="utf-8")
    return applied


def _build_pr_body(
    updates: list[tuple[str, str, str, str]],
    results: list[FrictionResult],
) -> str:
    result_map = {r["name"].lower(): r for r in results}
    lines = [
        "## scori dependency updates",
        "",
        "Generated by `scori fix`. Ordered by friction score (lowest risk first).",
        "",
        "| Package | Current | Latest | Jump | Score | Label |",
        "|---------|---------|--------|------|------:|-------|",
    ]
    label_emoji = {"Low": "🟢", "Medium": "🟡", "High": "🟠", "Critical": "🔴"}
    for name, current, latest, _ in updates:
        r = result_map.get(name.lower())
        if r:
            emoji = label_emoji.get(r["label"], "⚪")
            lines.append(
                f"| {name} | {current} | {latest} "
                f"| {r['version_jump']} | {r['score']} | {emoji} {r['label']} |"
            )
        else:
            lines.append(f"| {name} | {current} | {latest} | — | — | — |")
    lines += [
        "",
        "---",
        "_Generated by [scori](https://github.com/pauloestevao795/scori) — "
        "Software Composition Risk Intelligence_",
    ]
    return "\n".join(lines)


def create_pr(
    project_root: Path,
    updates: list[tuple[str, str, str, str]],
    results: list[FrictionResult],
    base_branch: str | None = None,
    dry_run: bool = True,
) -> dict[str, Any]:
    """Create a GitHub PR with the recommended dependency updates.

    updates: list of (name, current_version, latest_version, source_file)
    Returns dict with keys: branch, pr_url, applied.
    In dry_run mode, no git operations are performed.
    """
    from datetime import datetime

    token = os.environ.get("GITHUB_TOKEN")
    base = base_branch or current_branch(project_root)
    branch_name = f"fix/scori-updates-{datetime.now().strftime('%Y%m%d-%H%M%S')}"

    pkg_count = len(updates)
    noun = "dependency" if pkg_count == 1 else "dependencies"
    pr_title = f"chore(deps): scori — update {pkg_count} {noun}"
    pr_body = _build_pr_body(updates, results)

    if dry_run:
        return {"branch": branch_name, "pr_url": None, "applied": 0, "dry_run": True}

    if not token:
        raise ValueError(
            "GITHUB_TOKEN is required. Export it or set it in your environment."
        )
    owner_repo = detect_github_remote(project_root)
    if not owner_repo:
        raise ValueError(
            "Could not detect GitHub remote. "
            "Make sure 'origin' points to a GitHub repo."
        )
    owner, repo = owner_repo

    if has_uncommitted_changes(project_root):
        raise ValueError(
            "Working directory has uncommitted changes. Commit or stash them first."
        )

    rc, _ = _git(["checkout", "-b", branch_name], project_root)
    if rc != 0:
        raise RuntimeError(f"Failed to create branch {branch_name!r}.")

    try:
        applied = _apply_updates(project_root, updates)
        _git(["add", "--all"], project_root)

        top_pkgs = ", ".join(n for n, _, _, _ in updates[:3])
        if pkg_count > 3:
            top_pkgs += f" and {pkg_count - 3} more"
        _git(
            ["commit", "-m", f"chore(deps): update {top_pkgs} (scori fix)"],
            project_root,
        )
        _git(["push", "origin", branch_name], project_root)

        r = requests.post(
            f"https://api.github.com/repos/{owner}/{repo}/pulls",
            headers={
                "Authorization": f"Bearer {token}",
                "Accept": "application/vnd.github+json",
                "X-GitHub-Api-Version": "2022-11-28",
            },
            json={
                "title": pr_title,
                "body": pr_body,
                "head": branch_name,
                "base": base,
            },
            timeout=15,
        )
        if not r.ok:
            raise RuntimeError(f"GitHub API error {r.status_code}: {r.text[:300]}")

        pr_url: str = r.json().get("html_url", "")
    except Exception:
        _git(["checkout", base], project_root)
        _git(["branch", "-D", branch_name], project_root)
        raise
    finally:
        _git(["checkout", base], project_root)

    return {
        "branch": branch_name,
        "pr_url": pr_url,
        "applied": applied,
        "dry_run": False,
    }
